# Copyright 2020 ETH Zurich and University of Bologna.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: Paul Scheffler, ETH Zurich
#         Matheus Cavalcante, ETH Zurich

variables:
  GIT_SUBMODULE_STRATEGY: none
  RUST_LOG: 'memora=debug'
  PATH: '/home/gitlabci/.cargo/bin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/usr/local/condor/bin:/usr/sepp/bin'
  CCACHE_DIR: $CI_PROJECT_DIR/.ccache

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_NAME

before_script:
  - env
  - git submodule sync --recursive
  - git submodule foreach --recursive git reset --hard

after_script:
  - env

stages:
  - toolchain
  - compile
  - simulate

#####################
#  Toolchain stage  #
#####################

tc-gcc:
  stage: toolchain
  script:
    - |
      if ! $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh lookup tc-gcc; then
        git submodule update --init --recursive -- toolchain/riscv-gnu-toolchain
        mkdir -p /usr/scratch2/dolent1/gitlabci/buildcache/ara
        make toolchain
        $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert tc-gcc
      fi

tc-isa-sim:
  stage: toolchain
  script:
    - git submodule update --init --recursive -- toolchain/riscv-isa-sim
    - git submodule foreach --recursive git reset --hard
    - rm -rf toolchain/riscv-isa-sim/build
    - make riscv-isa-sim
  artifacts:
    paths:
      - install/riscv-isa-sim
    expire_in: 1 day

###################
#  Compile stage  #
###################

compile_apps:
  stage: compile
  script:
    - git submodule update --init --recursive -- apps/riscv-tests
    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-gcc
    - make -C apps
  artifacts:
    paths:
      - apps/bin
  needs: ["tc-gcc"]

compile_riscv_tests:
  stage: compile
  script:
    - git submodule update --init --recursive -- toolchain/riscv-isa-sim
    - git submodule update --init --recursive -- apps/riscv-tests
    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-gcc
    - make -C apps riscv_tests
  artifacts:
    paths:
      - apps/bin
  needs: ["tc-gcc"]

compile_ara:
  stage: compile
  script:
    - export CCACHE_DIR=$CI_PROJECT_DIR/.ccache
    - git submodule update --init --recursive -- toolchain/verilator
    - git submodule foreach --recursive git reset --hard
    - rm -rf install/verilator
    - make verilator
    - veril_trace=0 make -C hardware verilate
  artifacts:
    paths:
      - hardware/build/verilator/Vara_tb_verilator

####################
#  Simulate stage  #
####################

hello_world:
  stage: simulate
  script:
    - make -C hardware app=${CI_JOB_NAME} simc
  artifacts:
    paths:
      - hardware/build/trace_hart_*.log
      - hardware/build/transcript

riscv_tests_simv:
  stage: simulate
  script:
    - git submodule update --init --recursive -- apps/riscv-tests
    - make -C hardware riscv_tests_simv
  needs: ["tc-gcc", "compile_riscv_tests", "compile_ara"]
  dependencies:
    - tc-gcc
    - compile_riscv_tests
    - compile_ara

riscv_tests_spike:
  stage: simulate
  script:
    - git submodule update --init --recursive -- apps/riscv-tests
    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-gcc
    - make -C apps/riscv-tests/isa clean
    - make -C apps riscv_tests_spike
  artifacts:
    paths:
      - apps/riscv-tests/isa/*.dump
      - apps/riscv-tests/isa/*.out32
  needs: ["tc-isa-sim", "tc-gcc", "compile_riscv_tests"]
  dependencies:
    - tc-isa-sim
    - tc-gcc
    - compile_riscv_tests
