"""
Constants.
"""

VLEN = 4096
vlenb = VLEN // 8

ISA_PATH = ""
BASE_PATH = ISA_PATH + "rv64uv/"

"""
	1. Run python3 generate.py with all files as it is except with VLEN = ? of your choice in this very file
	2. The macros and header file changes are very specific to the tests generated by this generator, other sourced tests 		should properly bring their own header and macros files
"""
