# Copyright 2021 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
#
# Author: Matheus Cavalcante <matheusd@iis.ee.ethz.ch>

# Lint the design
name: lint
on: [push, pull_request]

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install Python requirements
      run: pip install -r python-requirements.txt
    - name: Check license
      run: python scripts/licence-checker.py --config scripts/licence-checker.hjson hardware

  check-clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install Python requirements
      run: pip install -r python-requirements.txt
    - name: Install clang-format
      run: sudo apt-get install clang-format
    - name: Run clang-format
      run: |
        for file in `find apps -type f -name "*.[c|h|cpp|hpp]" | grep -vP "apps/riscv-tests"`; do
          ./scripts/run-clang-format.py --clang-format-executable clang-format $file || EXIT_STATUS=$?
        done
        exit $EXIT_STATUS
